import {BadRequestException,Injectable,NotFoundException} from '@nestjs/common';
import {DatabaseService} from '../database/database.service.js';
import {AuditService} from '../audit/audit.service.js';
type Ctx={actorUserId?:string;ipAddress?:string;userAgent?:string};
@Injectable()
export class InternalChatService{
 constructor(private readonly db:DatabaseService,private readonly audit:AuditService){}
 async channels(roleCode:string){const admin=['SUPER_ADMIN','OPERATIONS_MANAGER','SALES_MANAGER'].includes(roleCode);return (await this.db.query(`SELECT c.*,(SELECT COUNT(*)::int FROM internal_chat_messages m WHERE m.channel_id=c.id) AS message_count FROM internal_chat_channels c WHERE c.is_active=TRUE AND (c.visibility='ALL_STAFF' OR $1::boolean=TRUE) ORDER BY CASE WHEN c.name='General' THEN 0 ELSE 1 END,c.name`,[admin])).rows}
 async createChannel(body:{name?:string;description?:string;visibility?:string},ctx?:Ctx){const name=body.name?.trim();if(!name)throw new BadRequestException('Channel name is required');const visibility=body.visibility==='ADMIN_ONLY'?'ADMIN_ONLY':'ALL_STAFF';try{const row=(await this.db.query(`INSERT INTO internal_chat_channels(name,description,visibility,created_by_id) VALUES($1,$2,$3,$4) RETURNING *`,[name,body.description?.trim()||null,visibility,ctx?.actorUserId??null])).rows[0];await this.audit.log({actorUserId:ctx?.actorUserId,action:'CHAT_CHANNEL_CREATED',module:'communications',entityType:'chat_channel',entityId:String(row.id),newValues:row,ipAddress:ctx?.ipAddress,userAgent:ctx?.userAgent});return row}catch(error:any){if(error?.code==='23505')throw new BadRequestException('A channel with this name already exists');throw error}}
 async messages(channelId:string,roleCode:string,before?:string){await this.ensureAccess(channelId,roleCode);const result=await this.db.query(`SELECT m.*,u.first_name,u.last_name,u.job_title FROM internal_chat_messages m LEFT JOIN users u ON u.id=m.sender_user_id WHERE m.channel_id=$1 AND ($2::timestamptz IS NULL OR m.created_at<$2::timestamptz) ORDER BY m.created_at DESC LIMIT 80`,[channelId,before||null]);return result.rows.reverse()}
 async send(channelId:string,body:string,userId:string,roleCode:string){await this.ensureAccess(channelId,roleCode);const text=body?.trim();if(!text)throw new BadRequestException('Message cannot be empty');if(text.length>4000)throw new BadRequestException('Message is too long');return (await this.db.query(`INSERT INTO internal_chat_messages(channel_id,sender_user_id,body) VALUES($1,$2,$3) RETURNING *`,[channelId,userId,text])).rows[0]}
 private async ensureAccess(id:string,roleCode:string){const result=await this.db.query<{visibility:string}>(`SELECT visibility FROM internal_chat_channels WHERE id=$1 AND is_active=TRUE LIMIT 1`,[id]);const channel=result.rows[0];if(!channel)throw new NotFoundException('Chat channel not found');if(channel.visibility==='ADMIN_ONLY'&&!['SUPER_ADMIN','OPERATIONS_MANAGER','SALES_MANAGER'].includes(roleCode))throw new NotFoundException('Chat channel not found')}
}
