BEGIN;

ALTER TABLE letter_documents
  ADD COLUMN IF NOT EXISTS signature_scale NUMERIC(4,2) NOT NULL DEFAULT 1.00,
  ADD COLUMN IF NOT EXISTS signature_offset_x INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS signature_offset_y INTEGER NOT NULL DEFAULT 0;

COMMIT;
