import {BadRequestException,Injectable,UnauthorizedException} from '@nestjs/common';
import {createCipheriv,createDecipheriv,createHmac,randomBytes} from 'node:crypto';
import {DatabaseService} from '../database/database.service.js';
import {AuditService} from '../audit/audit.service.js';

@Injectable()
export class GmailService{
 constructor(private readonly db:DatabaseService,private readonly audit:AuditService){}

 private config(){
  const clientId=process.env.GOOGLE_OAUTH_CLIENT_ID;
  const clientSecret=process.env.GOOGLE_OAUTH_CLIENT_SECRET;
  const redirectUri=process.env.GOOGLE_OAUTH_REDIRECT_URI ?? 'http://localhost:4000/api/integrations/google/callback';
  const encryptionKey=process.env.GOOGLE_TOKEN_ENCRYPTION_KEY;
  if(!clientId||!clientSecret||!encryptionKey)throw new BadRequestException('Google Workspace integration is not configured. Add GOOGLE_OAUTH_CLIENT_ID, GOOGLE_OAUTH_CLIENT_SECRET and GOOGLE_TOKEN_ENCRYPTION_KEY.');
  return{clientId,clientSecret,redirectUri,encryptionKey,frontend:process.env.FRONTEND_URL??'http://localhost:3000'};
 }

 async status(userId:string){const row=(await this.db.query(`SELECT google_email,scope,connected_at,updated_at FROM google_mail_connections WHERE user_id=$1`,[userId])).rows[0];return{configured:Boolean(process.env.GOOGLE_OAUTH_CLIENT_ID&&process.env.GOOGLE_OAUTH_CLIENT_SECRET&&process.env.GOOGLE_TOKEN_ENCRYPTION_KEY),connected:Boolean(row),account:row??null}}

 connectUrl(userId:string){const c=this.config();const statePayload=`${userId}.${Date.now()}`;const sig=createHmac('sha256',c.encryptionKey).update(statePayload).digest('base64url');const state=Buffer.from(`${statePayload}.${sig}`).toString('base64url');const params=new URLSearchParams({client_id:c.clientId,redirect_uri:c.redirectUri,response_type:'code',access_type:'offline',prompt:'consent',state,scope:['openid','email','https://www.googleapis.com/auth/gmail.readonly','https://www.googleapis.com/auth/gmail.send','https://www.googleapis.com/auth/calendar.events'].join(' ')});return `https://accounts.google.com/o/oauth2/v2/auth?${params.toString()}`}

 async callback(code:string,state:string){const c=this.config();const decoded=Buffer.from(state,'base64url').toString('utf8');const parts=decoded.split('.');if(parts.length<3)throw new UnauthorizedException('Invalid Google connection state');const userId=parts[0],timestamp=Number(parts[1]),sig=parts.slice(2).join('.');const payload=`${userId}.${timestamp}`;const expected=createHmac('sha256',c.encryptionKey).update(payload).digest('base64url');if(sig!==expected||!Number.isFinite(timestamp)||Date.now()-timestamp>15*60_000)throw new UnauthorizedException('Google connection request expired');
  const token=await this.postForm('https://oauth2.googleapis.com/token',{code,client_id:c.clientId,client_secret:c.clientSecret,redirect_uri:c.redirectUri,grant_type:'authorization_code'});
  if(!token.refresh_token)throw new BadRequestException('Google did not return an offline refresh token. Disconnect the app in Google Account permissions and connect again.');
  const profile=await this.googleJson('https://gmail.googleapis.com/gmail/v1/users/me/profile',String(token.access_token));
  const encrypted=this.encrypt(String(token.refresh_token),c.encryptionKey);
  await this.db.query(`INSERT INTO google_mail_connections(user_id,google_email,encrypted_refresh_token,token_iv,token_tag,scope,connected_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,NOW(),NOW()) ON CONFLICT(user_id) DO UPDATE SET google_email=EXCLUDED.google_email,encrypted_refresh_token=EXCLUDED.encrypted_refresh_token,token_iv=EXCLUDED.token_iv,token_tag=EXCLUDED.token_tag,scope=EXCLUDED.scope,updated_at=NOW()`,[userId,String(profile.emailAddress??''),encrypted.data,encrypted.iv,encrypted.tag,String(token.scope??'')]);return `${c.frontend}/email?connected=1`;
 }

 async disconnect(userId:string){await this.db.query(`DELETE FROM google_mail_connections WHERE user_id=$1`,[userId]);return{connected:false}}

 async list(userId:string,q?:string){const access=await this.accessToken(userId);const params=new URLSearchParams({maxResults:'25'});if(q?.trim())params.set('q',q.trim());const list=await this.googleJson(`https://gmail.googleapis.com/gmail/v1/users/me/messages?${params}`,access);const ids=Array.isArray(list.messages)?list.messages.slice(0,25):[];const items=await Promise.all(ids.map(async(m:any)=>{const d=await this.googleJson(`https://gmail.googleapis.com/gmail/v1/users/me/messages/${m.id}?format=metadata&metadataHeaders=From&metadataHeaders=To&metadataHeaders=Subject&metadataHeaders=Date`,access);const headers=this.headers(d.payload?.headers);return{id:d.id,threadId:d.threadId,snippet:d.snippet??'',from:headers.From??'',to:headers.To??'',subject:headers.Subject??'(No subject)',date:headers.Date??'',labelIds:d.labelIds??[]}}));return items}

 async getMessage(userId:string,id:string){const access=await this.accessToken(userId);const d=await this.googleJson(`https://gmail.googleapis.com/gmail/v1/users/me/messages/${encodeURIComponent(id)}?format=full`,access);const headers=this.headers(d.payload?.headers);return{id:d.id,threadId:d.threadId,snippet:d.snippet??'',from:headers.From??'',to:headers.To??'',subject:headers.Subject??'(No subject)',date:headers.Date??'',body:this.extractBody(d.payload)}}

 async send(userId:string,input:{to?:string;subject?:string;body?:string;cc?:string|null;leadId?:string|null;organizationId?:string|null;contactId?:string|null}){const to=input.to?.trim(),subject=input.subject?.trim()??'',body=input.body?.trim();if(!to||!body)throw new BadRequestException('Recipient and message are required');const access=await this.accessToken(userId);const lines=[`To: ${to}`,input.cc?.trim()?`Cc: ${input.cc.trim()}`:null,`Subject: ${subject}`,'Content-Type: text/plain; charset="UTF-8"','MIME-Version: 1.0','',body].filter((x):x is string=>x!==null);const raw=Buffer.from(lines.join('\r\n')).toString('base64url');const sent=await this.googleJson('https://gmail.googleapis.com/gmail/v1/users/me/messages/send',access,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({raw})});await this.audit.log({actorUserId:userId,action:'GMAIL_MESSAGE_SENT',module:'communications',entityType:'gmail_message',newValues:{messageId:sent.id??null,to,subject,leadId:input.leadId??null,organizationId:input.organizationId??null,contactId:input.contactId??null}});return sent}

 async createCalendarEvent(userId:string,b:{title?:string;notes?:string;startsAt?:string;endsAt?:string;reminderMinutes?:number}){if(!b.title?.trim()||!b.startsAt)throw new BadRequestException('Title and start time are required');const token=await this.accessToken(userId);const start=new Date(b.startsAt);const end=b.endsAt?new Date(b.endsAt):new Date(start.getTime()+30*60*1000);const response=await fetch('https://www.googleapis.com/calendar/v3/calendars/primary/events',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({summary:b.title.trim(),description:b.notes||'',start:{dateTime:start.toISOString()},end:{dateTime:end.toISOString()},reminders:{useDefault:false,overrides:[{method:'popup',minutes:Number(b.reminderMinutes??30)}]}})});if(!response.ok)throw new BadRequestException('Unable to add this item to Google Calendar. Reconnect Google Workspace if Calendar access was added recently.');return response.json()}
 private async accessToken(userId:string){const row=(await this.db.query<{encrypted_refresh_token:string;token_iv:string;token_tag:string}>(`SELECT encrypted_refresh_token,token_iv,token_tag FROM google_mail_connections WHERE user_id=$1`,[userId])).rows[0];if(!row)throw new BadRequestException('Connect your Google mailbox first');const c=this.config();const refresh=this.decrypt(row.encrypted_refresh_token,row.token_iv,row.token_tag,c.encryptionKey);const token=await this.postForm('https://oauth2.googleapis.com/token',{client_id:c.clientId,client_secret:c.clientSecret,refresh_token:refresh,grant_type:'refresh_token'});if(!token.access_token)throw new BadRequestException('Unable to refresh Google mailbox access');return String(token.access_token)}
 private key(secret:string){return createHmac('sha256','planorahub-google-token').update(secret).digest()}
 private encrypt(value:string,secret:string){const iv=randomBytes(12);const cipher=createCipheriv('aes-256-gcm',this.key(secret),iv);const data=Buffer.concat([cipher.update(value,'utf8'),cipher.final()]);return{data:data.toString('base64'),iv:iv.toString('base64'),tag:cipher.getAuthTag().toString('base64')}}
 private decrypt(data:string,iv:string,tag:string,secret:string){const decipher=createDecipheriv('aes-256-gcm',this.key(secret),Buffer.from(iv,'base64'));decipher.setAuthTag(Buffer.from(tag,'base64'));return Buffer.concat([decipher.update(Buffer.from(data,'base64')),decipher.final()]).toString('utf8')}
 private async postForm(url:string,body:Record<string,string>){const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(body)});const json:any=await response.json();if(!response.ok)throw new BadRequestException(json.error_description??json.error??'Google OAuth request failed');return json}
 private async googleJson(url:string,token:string,init:RequestInit={}){const headers=new Headers(init.headers);headers.set('Authorization',`Bearer ${token}`);const response=await fetch(url,{...init,headers});const json:any=await response.json();if(!response.ok)throw new BadRequestException(json?.error?.message??'Google Gmail request failed');return json}
 private headers(input:any){const out:Record<string,string>={};for(const h of Array.isArray(input)?input:[])if(h?.name)out[String(h.name)]=String(h.value??'');return out}
 private extractBody(part:any):string{if(!part)return'';if(part.mimeType==='text/plain'&&part.body?.data)return Buffer.from(part.body.data,'base64url').toString('utf8');for(const child of Array.isArray(part.parts)?part.parts:[]){const value=this.extractBody(child);if(value)return value}if(part.body?.data)return Buffer.from(part.body.data,'base64url').toString('utf8');return''}
}
